image: Visual Studio 2019
version: '1.4.0-build{build}'
init:
  - if %APPVEYOR_REPO_TAG%==true (appveyor UpdateBuild -Version "%APPVEYOR_BUILD_VERSION%")
skip_branch_with_pr: true
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
configuration: Release
before_build:
  - appveyor-retry dotnet restore -v Minimal
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: KP/O2ZLXeVBNEESezCyg6aBv1zoRxUDc/67BPtmZotPgG6UkD3dTh4DFcg/cfGa7
    on:
      branch: develop
  - provider: NuGet
    api_key:
      secure: KP/O2ZLXeVBNEESezCyg6aBv1zoRxUDc/67BPtmZotPgG6UkD3dTh4DFcg/cfGa7
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: AppVeyor CI deployment
    auth_token:
      secure: IApJWoucWEA6qjZn1atyOtaEMbBJVMcs8r4AeTwX3yOPWYK76w6VzOpzG+eTainp
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true
